# Generated by Django 5.0.4 on 2025-05-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PsychiatricAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64)),
                ('timestamp', models.FloatField()),
                ('emotion', models.CharField(max_length=32)),
                ('anxiety_score', models.FloatField()),
                ('depression_score', models.FloatField()),
            ],
        ),
    ]
